### ISSUE TITLE
KeyError: 'RequestId'

### ISSUE THREAD

**Issue by LycanW** [Lancercmd/nonebot_plugin_translator#1]
![image](https://user-images.githubusercontent.com/87530173/126079496-40edc011-5c59-41fc-9652-66cc76f5772c.png)
一直会这样子报错无法解决

**Comment by Lancercmd** [comment]
已在最新的提交和 PyPI 对应 `2.0.0a13.post0` 版本修复了这个问题

使用 poetry venv 的话，需要使用 `poetry run python -m pip install -U nonebot-plugin-translator` 来更新到这个 post 版本

或者也可以用你喜好的方式来更新版本

**Comment by Lancercmd** [comment]
由于过去了很长时间，这个问题应该已经被解决，此 Issue 关闭
