### ISSUE TITLE
输入语种自动识别？

### ISSUE THREAD

**Issue by Xiao-yux** [Lancercmd/nonebot_plugin_translator#23]
![image](https://user-images.githubusercontent.com/79674967/185728597-6b4ef451-81e0-46e4-b811-f4dd8c772ce7.png)
能不能把这一步省略了，改成自动识别

**Comment by Lancercmd** [comment]
抱歉过这么久才回复。

### 需要确认输入和目标语种，和接口有关
需要确认输入和目标语种是接口定义所致，腾讯机器翻译对于输入和目标语种存在限制。

不同的输入语种可选的目标语种在 [API 文档](https://cloud.tencent.com/document/api/551/15619#2.-.E8.BE.93.E5.85.A5.E5.8F.82.E6.95.B0) 有明确定义，因此需要先确定输入和目标语种。

### 翻译功能本来就可以使用其他交互模式
将交互顺序更改为 先翻译内容后选择语种 其实本身就有支持，不过同样也是手动的。
```powershell
> 翻译你好
"请选择输入语种，可选值如下~
zh | zh-TW | en | ja | ko | fr | es | it | de | tr | ru | pt | vi | id | th | ms | ar | hi"

> zh
"请选择目标语种，可选值如下~
en | ja | ko | fr | es | it | de | tr | ru | pt | vi | id | th | ms"

> ja
"こんにちは"
```
也支持使用一句话命令来完成翻译，即在一句话中一次性提供合法的输入、目标语种和需要翻译的文字。
```powershell
> 翻译zh ja 你好
"こんにちは"
```
### 对于语种自动识别的可行性探索
根据上面所说的，我认为语种自动识别的不合理之处在于**它在即使没有真正进行文本翻译时也产生了网络请求**。

因此其实在这条 Issue 贴出后，花费了一段时间寻找离线的语种识别方法。

不过多数对中文，以及复数个语种的文本不友好，最终不了了之。
### 不过有好的变化了
近期提交的，用于连续文本翻译的翻译锁定模式 `翻译+` 不仅能避免多次设定输入和目标语种，

在文本翻译阶段前会对需要翻译的文字进行语种识别，一方面可以自动识别输入语种，同时也能避免产生接口定义外的组合。
### 但也并不是完全好
和所述的一样，为了避免产生接口定义外的语种组合，如果设定的目标语种是输入语种所不支持的，

翻译功能会自动修正目标语种，所以实际应用的目标语种和翻译结果可能改变（有提示）。
### 可能的解决办法
达到全部目标语种可用的方法也不是没有，那也就是使用英语作为中间语种。

不过如果应用到所有的翻译请求，那么单次翻译的请求相当于会需要两倍时间。

但如果只应用到所需的翻译请求，那相当于中间用英文翻译了一次，那最终的翻译结果又可能是有出入的。

所以目前就暂时这样了，如果有更合适的改进就到时候再说。
