### ISSUE TITLE
关于我遇到的问题（已解决）

### ISSUE THREAD

**Issue by verynewabie** [Lancercmd/nonebot_plugin_translator#51]
我是前几天刚买的云服务器，安装的OpenSSL是1.1.1版本，安装完这个插件，输入要翻译的内容后就报错，如下图所示：
![image-20230424152658022](https://cartoonwqy.oss-cn-nanjing.aliyuncs.com/boke/202304241526113.png)
![image-20230424152744759](https://cartoonwqy.oss-cn-nanjing.aliyuncs.com/boke/202304241527790.png)
然后找到了这篇文章解决了问题：[【Python】解决SSL certificate problem unable to get local issuer certificate](https://blog.musnow.top/posts/3348986841/)，如果你在验证主机是否能成功连接到kaiheila.cn(kookapp.cn) 并认证ssl证书的时候也失败了，不用管，直接按下面的解决方法做就行了。（我就是这样的）

**Comment by Lancercmd** [comment]
因为服务器环境本身存在问题，或对目标服务器 SSL 证书验证存在问题导致需要忽略验证 SSL 证书才能正常工作的情况，可以对有关部分实现进行改动。
```python
    ...
    async with request("POST", url, data=params) as resp:
        ...
```
```python
from aiohttp.connector import TCPConnector

connector = TCPConnector(verify_ssl=False)
    ...
    async with request("POST", url, data=params, connector=connector) as resp:
        ...
```
应该就能行了，但因此产生的潜在风险应自行控制。

**Comment by verynewabie** [comment]
对的，是我服务器本身的环境有问题，已解决
